services:
  app:
    build: ./backend
    container_name: integracja-systemow-app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development        # auto-reload templates
    volumes:
      - ./backend/app:/srv/app/app   # hot-reload code during dev (optional)

  db:
    image: mysql:8.4
    container_name: integracja-systemow-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: integracja
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot"]
      interval: 5s
      retries: 10
