services:
  app:
    build: ./backend
    environment:
      - FLASK_APP=app
      - DB_HOST=db
      - DB_USER=app
      - DB_PASS=app
      - DB_NAME=integracja
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=integracja
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  dbdata:
